default_language_version:
    python: python3.11
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-ast
  - id: debug-statements
  - id: check-toml
  - id: check-xml
  - id: trailing-whitespace
  - id: check-json
  - id: sort-simple-yaml

- repo: https://github.com/sirosen/fix-smartquotes
  rev: 0.1.1
  hooks:
    - id: fix-smartquotes




exclude: migrations
