repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        additional_dependencies: ["isort==5.9.3"]
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-black
    rev: v22.0.2
    hooks:
      - id: black
        additional_dependencies: ["black==22.0.2"]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8==4.0.1"]

  - repo: https://github.com/pre-commit/mirrors-docker-compose
    rev: v2.2.2
    hooks:
      - id: docker-compose-config-check
        args: ["-f", "docker-compose.yaml", "docker-compose.dev.yaml", "docker-compose.prod.yaml", "config"]
