version: "3.8"
services:
  redis:
    image: redis:alpine
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      PGUSER: ${DATABASE_USERNAME:-postgres}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD:-password}
    restart: always

  app:
    build: .
    image: simple2b/tenkabel:latest
    restart: always
    command: bash ./start_server.sh
    env_file:
      - .env
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-password}@db/db
      SERVER_PORT: ${SERVER_PORT:-8008}
    volumes:
      - ./firebase_credentials.json:/app/firebase_credentials.json
      - ./google_cloud_service_account.json:/app/google_cloud_service_account.json
    ports:
      - 127.0.0.1:${SERVER_PORT:-8008}:80
    depends_on:
      - db

  worker:
    build: .
    image: simple2b/tenkabel-be:latest
    restart: always
    command: bash ./start_worker.sh
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-password}@db/db
      REDIS_URL: redis://:${REDIS_PASSWORD:-password}@redis
    depends_on:
      - redis

volumes:
  db_data:
