version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    env_file:
      - project.env
    ports:
      - 127.0.0.1:${REDIS_PORT:-6385}:6379
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-password}
    command: >
      --requirepass ${REDIS_PASSWORD:-password}

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      PGUSER: ${DATABASE_USERNAME:-postgres}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5433}:5432
    restart: always

  app:
    image: simple2b/tenkabel:latest # TODO change tag to actual backend version
    restart: always
    command: bash ./start_server.sh
    env_file:
      - project.env
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-password}@db/db
      SERVER_PORT: ${SERVER_PORT:-8008}
    volumes:
      - ./firebase_credentials.json:/app/firebase_credentials.json
      - ./google_cloud_service_account.json:/app/google_cloud_service_account.json
    ports:
      - 127.0.0.1:${SERVER_PORT:-8008}:80
    depends_on:
      - db

  worker:
    image: simple2b/tenkabel:latest # TODO change tag to actual backend version
    restart: always
    env_file:
      - project.env
    command: bash ./start_worker.sh
    environment:
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-password}@db/db
      REDIS_URL: redis://:${REDIS_PASSWORD:-password}@redis
      REDIS_PORT: ${REDIS_PORT:-6385}
    depends_on:
      - redis

volumes:
  db_data:
