"""notification_route

Revision ID: 1133f1b3c3c5
Revises: 3ccfd575a4da
Create Date: 2023-06-23 14:50:02.016501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1133f1b3c3c5"
down_revision = "3ccfd575a4da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_notifications_locations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_users_notifications_locations_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_notifications_locations_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "location_id", name=op.f("pk_users_notifications_locations")
        ),
    )
    op.create_table(
        "users_notifications_professions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("profession_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
            name=op.f("fk_users_notifications_professions_profession_id_professions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_notifications_professions_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "profession_id", name=op.f("pk_users_notifications_professions")
        ),
    )
    op.add_column(
        "users", sa.Column("notification_profession_flag", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("notification_locations_flag", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("notification_job_status", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notification_job_status")
    op.drop_column("users", "notification_locations_flag")
    op.drop_column("users", "notification_profession_flag")
    op.drop_table("users_notifications_professions")
    op.drop_table("users_notifications_locations")
    # ### end Alembic commands ###
