"""profession_is_deleted

Revision ID: 1d72bf335675
Revises: 586865558d3c
Create Date: 2023-12-04 15:13:34.848424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d72bf335675"
down_revision = "586865558d3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("professions", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.execute("UPDATE professions SET is_deleted = false")
    op.alter_column("professions", "is_deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("professions", "is_deleted")
    # ### end Alembic commands ###
