"""commission_status_update

Revision ID: 1f2c8a20f677
Revises: 75feeaf44f89
Create Date: 2023-07-04 09:01:58.568407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f2c8a20f677"
down_revision = "75feeaf44f89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE commissionstatus ADD VALUE IF NOT EXISTS 'REQUESTED' AFTER 'UNPAID'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
