"""user_payplus

Revision ID: 258a15f78733
Revises: c8ddb638b1fd
Create Date: 2023-06-29 12:43:09.140341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "258a15f78733"
down_revision = "c8ddb638b1fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("payplus_customer_uid", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "users", sa.Column("payplus_card_uid", sa.String(length=36), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_users_payplus_card_uid"), "users", ["payplus_card_uid"]
    )
    # ### end Alembic commands ###
    op.alter_column("users", "payplus_customer_uid", length=64, nullable=True)
    op.alter_column("users", "payplus_card_uid", length=64, nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_payplus_card_uid"), "users", type_="unique")
    op.drop_column("users", "payplus_card_uid")
    op.drop_column("users", "payplus_customer_uid")
    # ### end Alembic commands ###
