"""empty message

Revision ID: 27c4ef79081a
Revises: 258a15f78733
Create Date: 2023-06-30 15:17:45.386161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c4ef79081a'
down_revision = '258a15f78733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_comissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('platform_payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'PENDING', 'PAID', name='platformcomissionstatus'), nullable=False),
    sa.Column('transaction_number', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_platform_comissions_job_id_jobs')),
    sa.ForeignKeyConstraint(['platform_payment_id'], ['platform_payments.id'], name=op.f('fk_platform_comissions_platform_payment_id_platform_payments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_platform_comissions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_comissions'))
    )
    op.add_column('platform_payments', sa.Column('type', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='platformpaymentperiod'), nullable=False))
    op.add_column('platform_payments', sa.Column('reject', sa.String(), nullable=False))
    op.add_column('platform_payments', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.drop_constraint('fk_platform_payments_job_id_jobs', 'platform_payments', type_='foreignkey')
    op.drop_column('platform_payments', 'job_id')
    op.drop_column('platform_payments', 'transaction_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_payments', sa.Column('transaction_number', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('platform_payments', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_platform_payments_job_id_jobs', 'platform_payments', 'jobs', ['job_id'], ['id'])
    op.drop_column('platform_payments', 'rejected_at')
    op.drop_column('platform_payments', 'reject')
    op.drop_column('platform_payments', 'type')
    op.drop_table('platform_comissions')
    # ### end Alembic commands ###
