"""app_review

Revision ID: 325132677a15
Revises: c0b1665c05d5
Create Date: 2023-10-16 12:37:09.868297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "325132677a15"
down_revision = "c0b1665c05d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("stars_count", sa.Integer(), nullable=False),
        sa.Column("review", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_app_reviews_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_reviews")),
    )
    op.create_index(op.f("ix_app_reviews_uuid"), "app_reviews", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_reviews_uuid"), table_name="app_reviews")
    op.drop_table("app_reviews")
    # ### end Alembic commands ###
