"""status_paid_job

Revision ID: 362ae768887b
Revises: 1133f1b3c3c5
Create Date: 2023-06-27 07:59:47.748277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362ae768887b'
down_revision = '1133f1b3c3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
