"""commission_status_update

Revision ID: 3a29707fb19e
Revises: 85cd783d00e0
Create Date: 2023-09-04 10:13:47.518108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a29707fb19e"
down_revision = "85cd783d00e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
