"""commission_status_update

Revision ID: 3a29707fb19e
Revises: 85cd783d00e0
Create Date: 2023-09-04 10:13:47.518108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a29707fb19e"
down_revision = "85cd783d00e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add to this collumn sa.Column('commission_status', sa.Enum('PAID', 'UNPAID', 'REQUESTED', name='commissionstatus'), nullable=False), new enum values "Deny" and "Confirm"
    op.alter_column(
        "jobs",
        "commission_status",
        existing_type=sa.Enum(
            "paid", "unpaid", "requested", "deny", "confirm", name="commissionstatus"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "commission_status",
        existing_type=sa.Enum("PAID", "UNPAID", "REQUESTED", name="commissionstatus"),
        nullable=False,
    )
    # ### end Alembic commands ###
