"""empty message

Revision ID: 3a647bf455e1
Revises: 27c4ef79081a
Create Date: 2023-07-03 14:47:43.121804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a647bf455e1'
down_revision = '27c4ef79081a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_comissions', 'transaction_number')
    op.drop_column('platform_comissions', 'paid_at')
    op.drop_column('platform_comissions', 'status')
    op.add_column('platform_payments', sa.Column('period_type', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='platformpaymentperiod'), nullable=False))
    op.add_column('platform_payments', sa.Column('reject_reason', sa.String(length=512), nullable=False))
    op.add_column('platform_payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('platform_payments', 'type')
    op.drop_column('platform_payments', 'reject')
    op.add_column('users', sa.Column('platform_payment', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_platform_payment_platform_payments'), 'users', 'platform_payments', ['platform_payment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_platform_payment_platform_payments'), 'users', type_='foreignkey')
    op.drop_column('users', 'platform_payment')
    op.add_column('platform_payments', sa.Column('reject', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('platform_payments', sa.Column('type', postgresql.ENUM('WEEKLY', 'MONTHLY', 'YEARLY', name='platformpaymentperiod'), autoincrement=False, nullable=False))
    op.drop_column('platform_payments', 'created_at')
    op.drop_column('platform_payments', 'reject_reason')
    op.drop_column('platform_payments', 'period_type')
    op.add_column('platform_comissions', sa.Column('status', postgresql.ENUM('IDLE', 'PENDING', 'PAID', name='platformcomissionstatus'), autoincrement=False, nullable=False))
    op.add_column('platform_comissions', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('platform_comissions', sa.Column('transaction_number', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
