"""attacment

Revision ID: 4791b29c17b2
Revises: 9b0757283a5b
Create Date: 2023-09-08 16:08:55.373253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4791b29c17b2"
down_revision = "9b0757283a5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_files_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("url", name=op.f("uq_files_url")),
    )
    op.create_index(op.f("ix_files_uuid"), "files", ["uuid"], unique=True)
    op.add_column("attachments", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("attachments", sa.Column("file_id", sa.Integer(), nullable=True))
    op.add_column("attachments", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("attachments", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_constraint("uq_attachments_url", "attachments", type_="unique")
    op.drop_constraint(
        "fk_attachments_created_by_id_users", "attachments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_attachments_user_id_users"),
        "attachments",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_attachments_file_id_files"),
        "attachments",
        "files",
        ["file_id"],
        ["id"],
    )
    op.drop_column("attachments", "type")
    op.drop_column("attachments", "extension")
    op.drop_column("attachments", "storage_path")
    op.drop_column("attachments", "filename")
    op.drop_column("attachments", "created_by_id")
    op.drop_column("attachments", "url")
    op.drop_column("attachments", "uploaded_at")
    op.drop_column("attachments", "original_filename")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachments",
        sa.Column(
            "original_filename",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "attachments",
        sa.Column(
            "uploaded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "attachments",
        sa.Column("url", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "attachments",
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "attachments",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "attachments",
        sa.Column(
            "storage_path", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "attachments",
        sa.Column(
            "extension", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "attachments",
        sa.Column(
            "type",
            postgresql.ENUM("IMAGE", "DOCUMENT", name="attachmenttype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_attachments_file_id_files"), "attachments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_attachments_user_id_users"), "attachments", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_attachments_created_by_id_users",
        "attachments",
        "users",
        ["created_by_id"],
        ["id"],
    )
    op.create_unique_constraint("uq_attachments_url", "attachments", ["url"])
    op.drop_column("attachments", "is_deleted")
    op.drop_column("attachments", "created_at")
    op.drop_column("attachments", "file_id")
    op.drop_column("attachments", "user_id")
    op.drop_index(op.f("ix_files_uuid"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
