"""empty message

Revision ID: 50550206c693
Revises: b1af44a0d0ec
Create Date: 2023-10-25 12:48:25.665632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "50550206c693"
down_revision = "b1af44a0d0ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "commission_symbol",
        existing_type=postgresql.ENUM("PERCENT", "SHEKEL", name="commissionsymbol"),
        nullable=True,
        existing_server_default=sa.text("'PERCENT'::commissionsymbol"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "commission_symbol",
        existing_type=postgresql.ENUM("PERCENT", "SHEKEL", name="commissionsymbol"),
        nullable=True,
        existing_server_default=sa.text("'PERCENT'::commissionsymbol"),
    )
    # ### end Alembic commands ###
