"""professions

Revision ID: 586865558d3c
Revises: cfb8984b18ae
Create Date: 2023-11-01 17:01:45.424957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "586865558d3c"
down_revision = "cfb8984b18ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
