"""user_is_deleted

Revision ID: 60ac1052124e
Revises: 07aad891086b
Create Date: 2023-07-17 18:30:38.269603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60ac1052124e"
down_revision = "07aad891086b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("superusers", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET is_deleted = false")
    op.alter_column("users", "is_deleted", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    op.drop_column("superusers", "is_deleted")
    # ### end Alembic commands ###
