"""empty message

Revision ID: 653c4afaa300
Revises: 4a23fc7dad66
Create Date: 2023-09-01 10:38:19.342682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653c4afaa300'
down_revision = '4a23fc7dad66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('storage_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'storage_path')
    # ### end Alembic commands ###
