"""card_name

Revision ID: 75feeaf44f89
Revises: 258a15f78733
Create Date: 2023-07-03 11:18:26.886062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75feeaf44f89'
down_revision = '258a15f78733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'card_name')
    # ### end Alembic commands ###
