"""empty message

Revision ID: 80759281244c
Revises: 9dfb2c46291d
Create Date: 2023-06-13 16:32:57.635671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80759281244c'
down_revision = '9dfb2c46291d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('formated_time', sa.String(length=64), nullable=False))
    op.drop_column('jobs', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('time', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'formated_time')
    # ### end Alembic commands ###
