"""attachments_additional

Revision ID: 85cd783d00e0
Revises: d414af46df82
Create Date: 2023-09-04 09:47:09.785186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85cd783d00e0"
down_revision = "d414af46df82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachments", sa.Column("created_by_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_attachments_created_by_id_users"),
        "attachments",
        "users",
        ["created_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_attachments_created_by_id_users"), "attachments", type_="foreignkey"
    )
    op.drop_column("attachments", "created_by_id")
    # ### end Alembic commands ###
