"""payment_enum

Revision ID: 8af58fc33c5d
Revises: f1db37e1f581
Create Date: 2023-09-15 15:57:45.420153

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "8af58fc33c5d"
down_revision = "f1db37e1f581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """add to paymentstatus enum new values: DENY, CONFIRM, REQUESTED"""
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'DENY' AFTER 'UNPAID';")
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'REQUESTED' AFTER 'DENY';")
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'CONFIRM' AFTER 'REQUESTED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """remove from paymentstatus enum values: DENY, CONFIRM, REQUESTED"""
    op.execute("ALTER TYPE paymentstatus RENAME TO paymentstatus_old")
    op.execute("CREATE TYPE paymentstatus AS ENUM ('UNPAID', 'PAID')")
    op.execute(
        "ALTER TABLE payment ALTER COLUMN status TYPE paymentstatus USING status::text::paymentstatus"
    )
    op.execute("DROP TYPE paymentstatus_old")
    # ### end Alembic commands ###
