"""empty message

Revision ID: 974d6c3bac20
Revises: 717dd32ae0b5
Create Date: 2023-06-08 17:19:51.682729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974d6c3bac20'
down_revision = '717dd32ae0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superusers', sa.Column('picture', sa.Text(), nullable=False))
    op.drop_column('superusers', 'avatar_encoded')
    op.add_column('users', sa.Column('picture', sa.Text(), nullable=False))
    op.drop_column('users', 'avatar_encoded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_encoded', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'picture')
    op.add_column('superusers', sa.Column('avatar_encoded', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('superusers', 'picture')
    # ### end Alembic commands ###
