"""payment_enum_update

Revision ID: 9c111eecaeea
Revises: 15c918b416f4
Create Date: 2023-09-20 16:26:27.665865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c111eecaeea"
down_revision = "15c918b416f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE paymentstatus ADD VALUE 'SENT' AFTER 'PAID';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """remove from paymentstatus enum values: DENY, CONFIRM, REQUESTED"""
    op.execute("ALTER TYPE paymentstatus RENAME TO paymentstatus_old")
    op.execute(
        "CREATE TYPE paymentstatus AS ENUM ('REQUESTED', 'UNPAID', 'DENY', 'CONFIRM', 'PAID')"
    )
    op.execute(
        "ALTER TABLE jobs ALTER COLUMN commission_status TYPE paymentstatus USING commission_status::text::paymentstatus"
    )
    op.execute("DROP TYPE paymentstatus_old")
    # ### end Alembic commands ###
