"""empty message

Revision ID: a51fe6ffc264
Revises: 3dd9e98f56aa
Create Date: 2023-06-06 15:24:28.553802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51fe6ffc264'
down_revision = '3dd9e98f56aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
