"""empty message

Revision ID: bf8ff18943fa
Revises: 1e0914c9fd66
Create Date: 2023-07-04 11:56:49.943709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf8ff18943fa'
down_revision = '1e0914c9fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_comissions', 'platform_payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('platform_payments', 'period_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_payments', sa.Column('period_type', postgresql.ENUM('WEEKLY', 'MONTHLY', 'YEARLY', name='platformpaymentperiod'), autoincrement=False, nullable=False))
    op.alter_column('platform_comissions', 'platform_payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
