"""tags_changes

Revision ID: c0b1665c05d5
Revises: 5e53a5d70939
Create Date: 2023-10-10 12:02:12.389062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0b1665c05d5"
down_revision = "5e53a5d70939"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tags_profession_id_professions", "tags", type_="foreignkey")
    op.drop_column("tags", "profession_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags",
        sa.Column("profession_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_tags_profession_id_professions",
        "tags",
        "professions",
        ["profession_id"],
        ["id"],
    )
    # ### end Alembic commands ###
