"""notification_enums_update

Revision ID: c1f628cd12fb
Revises: 3169bfc78721
Create Date: 2023-10-03 13:03:18.680255

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c1f628cd12fb"
down_revision = "3169bfc78721"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE 'COMMISSION_DENIED' AFTER 'COMMISSION_PAID';"
    )
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE 'COMMISSION_SENT' AFTER 'COMMISSION_DENIED';"
    )
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE 'PAYMENT_REQUESTED' AFTER 'COMMISSION_SENT';"
    )
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE 'PAYMENT_SENT' AFTER 'PAYMENT_REQUESTED';"
    )
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE 'PAYMENT_DENIED' AFTER 'PAYMENT_SENT';"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtype RENAME TO notificationtype_old")
    op.execute(
        "CREATE TYPE notificationtype AS ENUM ('JOB_PAID', 'COMMISSION_REQUESTED', 'COMMISSION_PAID', 'COMMISSION_SENT', 'PAYMENT_REQUESTED', 'PAYMENT_SENT', 'PAYMENT_DENIED', 'MAX_JOB_TYPE', 'APPLICATION_CREATED', 'APPLICATION_ACCEPTED', 'APPLICATION_REJECTED', 'MAX_APPLICATION_TYPE')"
    )
    op.execute(
        "ALTER TABLE notifications ALTER COLUMN type TYPE notificationtype USING type::text::notificationtype"
    )
    op.execute("DROP TYPE notificationtype_old")
    # ### end Alembic commands ###
