"""payment id date

Revision ID: c8ddb638b1fd
Revises: a995b06e4777
Create Date: 2023-06-28 12:03:40.398639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8ddb638b1fd"
down_revision = "a995b06e4777"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platform_payments",
        sa.Column("transaction_number", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "platform_payments",
        sa.Column("paid_at", sa.DateTime(timezone=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("platform_payments", "paid_at")
    op.drop_column("platform_payments", "transaction_number")
    # ### end Alembic commands ###
