"""user model updated

Revision ID: c94629ea4ae0
Revises: c62fa5f2f6c3
Create Date: 2023-05-22 15:43:55.808183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94629ea4ae0'
down_revision = 'c62fa5f2f6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superusers', sa.Column('google_openid_key', sa.String(length=64), nullable=True))
    op.add_column('superusers', sa.Column('picture', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('google_openid_key', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'google_openid_key')
    op.drop_column('superusers', 'picture')
    op.drop_column('superusers', 'google_openid_key')
    # ### end Alembic commands ###
