"""attachments

Revision ID: d414af46df82
Revises: 5610196a54b9
Create Date: 2023-09-01 12:36:53.919110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d414af46df82"
down_revision = "5610196a54b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=True),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column(
            "type", sa.Enum("IMAGE", "DOCUMENT", name="attachmenttype"), nullable=False
        ),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_attachments_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("url", name=op.f("uq_attachments_url")),
    )
    op.create_index(op.f("ix_attachments_uuid"), "attachments", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_uuid"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
