"""empty message

Revision ID: d63adbb10685
Revises: c62fa5f2f6c3
Create Date: 2023-05-23 16:59:27.908352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d63adbb10685"
down_revision = "c62fa5f2f6c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("customer_first_name", sa.String(length=128), nullable=False)
    )
    op.add_column(
        "jobs", sa.Column("customer_last_name", sa.String(length=128), nullable=False)
    )
    op.add_column(
        "jobs", sa.Column("customer_phone", sa.String(length=128), nullable=False)
    )
    op.add_column(
        "jobs",
        sa.Column("customer_street_address", sa.String(length=128), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "customer_street_address")
    op.drop_column("jobs", "customer_phone")
    op.drop_column("jobs", "customer_last_name")
    op.drop_column("jobs", "customer_first_name")
    # ### end Alembic commands ###
