"""commission_requested_notification_type

Revision ID: d6e192a47fa9
Revises: 1f2c8a20f677
Create Date: 2023-07-04 11:36:48.268637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6e192a47fa9"
down_revision = "1f2c8a20f677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'COMMISSION_REQUESTED' AFTER 'JOB_PAID'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
