"""empty message

Revision ID: e2a69b330010
Revises: c8b628e628eb
Create Date: 2023-06-19 16:34:32.370683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2a69b330010"
down_revision = "c8b628e628eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "JOB_CREATED",
                "JOB_STARTED",
                "JOB_COMPLETED",
                "JOB_CANCELED",
                "JOB_PAID",
                "COMMISSION_PAID",
                "MAX_JOB_TYPE",
                "APPLICATION_CREATED",
                "APPLICATION_ACCEPTED",
                "APPLICATION_REJECTED",
                "MAX_APPLICATION_TYPE",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    # ### end Alembic commands ###
