"""apple_uid

Revision ID: eb42b5cfec2c
Revises: 60ac1052124e
Create Date: 2023-07-19 16:54:00.705931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb42b5cfec2c"
down_revision = "60ac1052124e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "superusers", sa.Column("apple_uid", sa.String(length=64), nullable=True)
    )
    op.add_column("users", sa.Column("apple_uid", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "apple_uid")
    op.drop_column("superusers", "apple_uid")
    # ### end Alembic commands ###
