"""notification_created_at

Revision ID: eb50279c329b
Revises: d4de3f3eb698
Create Date: 2023-06-20 10:56:05.990737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb50279c329b"
down_revision = "d4de3f3eb698"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications", sa.Column("created_at", sa.DateTime(), nullable=False)
    )

    ## add code to generate default value for created_at
    op.execute(
        "UPDATE notifications SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "created_at")
    # ### end Alembic commands ###
