"""empty message

Revision ID: eb675a1122e0
Revises: 653c4afaa300
Create Date: 2023-09-01 12:27:46.933210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb675a1122e0'
down_revision = '653c4afaa300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_attachments_url'), 'attachments', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attachments_url'), 'attachments', type_='unique')
    # ### end Alembic commands ###
