"""empty message

Revision ID: f3d56966ef4d
Revises: cc089b6a5e81
Create Date: 2023-05-30 15:24:05.614930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3d56966ef4d"
down_revision = "cc089b6a5e81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column(
            "rate",
            sa.Enum("POSITIVE", "NEGATIVE", "NEUTRAL", name="ratestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_rate_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["users.id"], name=op.f("fk_rate_worker_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate")
    # ### end Alembic commands ###
