"""job-payment

Revision ID: ff3ce51309c9
Revises: 1133f1b3c3c5
Create Date: 2023-06-26 17:32:03.609496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff3ce51309c9"
down_revision = "1133f1b3c3c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IDLE", "PENDING", "PAID", name="platformpaymentstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_platform_payments_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_platform_payments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_payments")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_payments")
    # ### end Alembic commands ###
