"""empty message

Revision ID: ffe97d4507ec
Revises: 05e869997b0b
Create Date: 2023-07-04 14:55:07.800949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffe97d4507ec"
down_revision = "05e869997b0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_commissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("platform_payment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_platform_commissions_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["platform_payment_id"],
            ["platform_payments.id"],
            name=op.f("fk_platform_commissions_platform_payment_id_platform_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_commissions_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_commissions")),
    )
    op.drop_table("platform_comissions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_comissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "platform_payment_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_platform_comissions_job_id_jobs"
        ),
        sa.ForeignKeyConstraint(
            ["platform_payment_id"],
            ["platform_payments.id"],
            name="fk_platform_comissions_platform_payment_id_platform_payments",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_platform_comissions_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_platform_comissions"),
    )
    op.drop_table("platform_commissions")
    # ### end Alembic commands ###
